// This file is now mostly redundant as the selectors are generated by createFeature in auth.reducer.ts
// We're exporting from the authFeature for backward compatibility
import {
  authFeature,
  selectUserPermissions,
  selectUserRole,
  selectIsSuperAdmin,
} from './auth.reducer';

// Export all the auto-generated selectors
export const {
  selectAuthState,
  selectUser,
  selectToken,
  selectIsAuthenticated,
  selectLoading,
  selectError,
} = authFeature;

// Export the custom selectors
export { selectUserPermissions, selectUserRole, selectIsSuperAdmin };
